apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: demo-plugin
spec:
  plugin:
    ipblacklist:
      StaticBlacklist:
      - "192.168.1.1"
      - "127.0.0.1"
      RealIPDepth: 0